module.exports={
    devServer:{
       proxy:{
           "/vip":{
               "target":"https://mapi.vip.com",
               "changeOrigin":true,
               "pathRewrite":{
                   "^/vip":"/"
               }
           }
       } 
    } 
 }